/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sells.struts.action.member;

import java.util.Collection;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionServlet;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import com.sells.common.util.HibernatePageAction;
import com.sells.common.util.PageControl;
import com.sells.dao.Member;
import com.sells.dao.Sells;
import com.sells.search.MemberSearch;
import com.sells.service.imp.MemberService;

/** 
 * MyEclipse Struts
 * Creation date: 09-04-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class MemberQueryAction extends HibernatePageAction {
  private MemberService memberService;
  private Log log = LogFactory.getLog(MemberQueryAction.class);
  private ServletContext servletContext;

  /*
   * (non-Javadoc)
   * 
   * @see org.apache.struts.action.Action#setServlet(org.apache.struts.action.ActionServlet)
   */
  public void setServlet(ActionServlet actionServlet) {
    super.setServlet(actionServlet);
    servletContext = actionServlet.getServletContext();
    WebApplicationContext wac = WebApplicationContextUtils
        .getRequiredWebApplicationContext(servletContext);
    this.memberService = (MemberService) wac.getBean("memberService");
  }

  @Override
  public ActionForward readPage(ActionMapping mapping, HttpServletRequest request, HttpServletResponse response, PageControl pagecontrol) {
    HttpSession session = request.getSession ();
    ActionErrors errors = new ActionErrors();
    try {
      Sells sells = (Sells) session.getAttribute("sells") ;
      if (sells == null ) {
        return mapping.findForward("sessionLost");
      }
      pagecontrol.setShowrows(20);
      MemberSearch search = new MemberSearch();
      search.setEmail(StringUtils.defaultString(request.getParameter("email")));
      search.setEpYn(StringUtils.defaultString(request.getParameter("epYn")));
      search.setName(StringUtils.defaultString(request.getParameter("name")));
      search.setStatus(StringUtils.defaultString(request.getParameter("status")));
      request.getSession().setAttribute("_SEARCH", search);
      if (StringUtils.defaultString(request.getParameter("search")).equals("")) {
        request.setAttribute("mainlist",null);
      } else {
        Collection<Member> list = memberService.findMemberBySearch(search,sells.getSellsNo(), pagecontrol) ;
        request.setAttribute("mainlist",list);
      }
    } catch (Exception e) {
      log.info(e.getMessage());
      errors.add("errMsg", new ActionError("alert.Error", e.getMessage()));
      saveErrors(request, errors);
      return mapping.findForward("error1");
    }
    return mapping.findForward("success");
  }

  @Override
  public int readSize(ActionMapping mapping, HttpServletRequest request, HttpServletResponse response, PageControl pagecontrol) {
    int rowSize = 0 ;
    HttpSession session = request.getSession ();
    try {
      Sells sells = (Sells) session.getAttribute("sells") ;
      String sellsNo = "" ;
      if (sells != null ) {
        sellsNo = sells.getSellsNo();
      }
      MemberSearch search = new MemberSearch();
      search.setEmail(StringUtils.defaultString(request.getParameter("email")));
      search.setEpYn(StringUtils.defaultString(request.getParameter("epYn")));
      search.setName(StringUtils.defaultString(request.getParameter("name")));
      search.setStatus(StringUtils.defaultString(request.getParameter("status")));
      pagecontrol.setShowrows(20);
      if (!StringUtils.defaultString(request.getParameter("search")).equals("")) {
        rowSize = memberService.findMemberBySearchSize(search,sellsNo) ;
      }
    } catch (Exception e) { log.debug(e.getMessage()); }
    return rowSize;
  }
}