/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sells.struts.action;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionServlet;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import com.sells.common.mail.Mail;
import com.sells.common.mail.MailBean;
import com.sells.common.util.EcServer;
import com.sells.dao.LoginData;
import com.sells.dao.Sells;
import com.sells.service.imp.SellsService;

/** 
 * MyEclipse Struts
 * Creation date: 02-03-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class OrderCarAction extends Action {
  private Log log = LogFactory.getLog(OrderCarAction.class);
  private SellsService sellsService ;
  private ServletContext servletContext;
  
  /* (non-Javadoc)
   * @see org.apache.struts.action.Action#setServlet(org.apache.struts.action.ActionServlet)
   */
  public void setServlet(ActionServlet actionServlet) {
      super.setServlet(actionServlet);
      servletContext = actionServlet.getServletContext();
      WebApplicationContext wac = WebApplicationContextUtils
              .getRequiredWebApplicationContext(servletContext);
      this.sellsService =  (SellsService) wac.getBean("sellsService");
  }

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
    HttpSession session = request.getSession ();
    try {
  		String orderTp = request.getParameter("orderTp");
      String orderMonth = request.getParameter("orderMonth");
      Sells sells= (Sells) session.getAttribute("sells") ;
      LoginData loginvo= (LoginData) session.getAttribute("loginvo") ;
      if (sells == null ) {
        return mapping.findForward("sessionLost");
      } else {
        //mail 通知
        sellsService.updateLoginData(loginvo);
        Sells admin = sellsService.findSellsById(EcServer.getAdminNo());
        StringBuffer sb = new StringBuffer();
        sb.append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
        sb.append("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
        sb.append("<head>");
        sb.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
        sb.append("<title>購買延長服務</title>");
        sb.append("</head>");
        sb.append("");
        sb.append("<body>");
        sb.append("<p><br />");
        sb.append("  親愛的 ").append(sells.getSellsNm()).append(" 您好：");
        sb.append("  <br />");
        sb.append("您購買的服務：").append(orderMonth).append("<br />  <br />");
        sb.append("請在48小時內完付款，請到<a href=\"").append(admin.getHomepage()).append("/Sells/help.jsp\">問題反應區</a>通知站長，將會為您開啟延長服務。  </p>");
        sb.append("<p>匯款方式：<br />");
        sb.append(StringUtils.defaultString(admin.getPayDesc()).replace("\n", "<BR>"));
        sb.append("</p>");
        sb.append("<p>站長敬上。</p>");
        sb.append("<p><a href=\"").append(admin.getHomepage()).append("\">").append(admin.getStoreNm()).append("</a></p>");
        sb.append("</body>");
        sb.append("</html>");

        MailBean mailBean = new MailBean();
        mailBean.setFrom(admin.getEmail());
        mailBean.setFromName(admin.getSellsNm());
        mailBean.setTo(sells.getEmail());
        mailBean.setToName(sells.getSellsNm());
        mailBean.setBcc(admin.getEmail());
        mailBean.setMailServer(EcServer.getMailServer());
        mailBean.setSubject(admin.getStoreNm()+ " - 購買延長服務");
        mailBean.setBody(sb.toString());
        mailBean.setCharset("UTF-8");
        try {
          Mail mail = new Mail(mailBean);
        } catch (Exception e) {
          log.info("GetPasswdAction mail e:" + e.getMessage());
        }
        sb = null ;
        admin = null ;
        session.setAttribute("sells", sells) ;
        session.setAttribute("loginvo", loginvo) ;
        return mapping.findForward("success");
      }
    } catch (Exception e ) {
      log.info("SellModi e:" + e.getMessage());
      return mapping.findForward("sessionLost");
    }
	}
}