package com.sells.dao;



/**
 * OrdersItemId generated by MyEclipse - Hibernate Tools
 */

public class OrdersItemId  implements java.io.Serializable {


    // Fields    

     private String orderNo;
     private Integer seqno;


    // Constructors

    /** default constructor */
    public OrdersItemId() {
    }

    
    /** full constructor */
    public OrdersItemId(String orderNo, Integer seqno) {
        this.orderNo = orderNo;
        this.seqno = seqno;
    }

   
    // Property accessors

    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public Integer getSeqno() {
        return this.seqno;
    }
    
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdersItemId) ) return false;
		 OrdersItemId castOther = ( OrdersItemId ) other; 
         
		 return ( (this.getOrderNo()==castOther.getOrderNo()) || ( this.getOrderNo()!=null && castOther.getOrderNo()!=null && this.getOrderNo().equals(castOther.getOrderNo()) ) )
 && ( (this.getSeqno()==castOther.getSeqno()) || ( this.getSeqno()!=null && castOther.getSeqno()!=null && this.getSeqno().equals(castOther.getSeqno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrderNo() == null ? 0 : this.getOrderNo().hashCode() );
         result = 37 * result + ( getSeqno() == null ? 0 : this.getSeqno().hashCode() );
         return result;
   }   





}