package com.sells.dao;



/**
 * OrdersItem generated by MyEclipse - Hibernate Tools
 */

public class OrdersItem  implements java.io.Serializable {


    // Fields    

     private OrdersItemId id;
     private String itemNo;
     private String itemNm;
     private String itemSpec1;
     private String itemSpec2;
     private Integer qty;
     private Integer price;


    // Constructors

    /** default constructor */
    public OrdersItem() {
    }

	/** minimal constructor */
    public OrdersItem(OrdersItemId id) {
        this.id = id;
    }
    
    /** full constructor */
    public OrdersItem(OrdersItemId id, String itemNo, String itemNm, String itemSpec1, String itemSpec2, Integer qty, Integer price) {
        this.id = id;
        this.itemNo = itemNo;
        this.itemNm = itemNm;
        this.itemSpec1 = itemSpec1;
        this.itemSpec2 = itemSpec2;
        this.qty = qty;
        this.price = price;
    }

   
    // Property accessors

    public OrdersItemId getId() {
        return this.id;
    }
    
    public void setId(OrdersItemId id) {
        this.id = id;
    }

    public String getItemNo() {
        return this.itemNo;
    }
    
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }

    public String getItemNm() {
        return this.itemNm;
    }
    
    public void setItemNm(String itemNm) {
        this.itemNm = itemNm;
    }

    public String getItemSpec1() {
        return this.itemSpec1;
    }
    
    public void setItemSpec1(String itemSpec1) {
        this.itemSpec1 = itemSpec1;
    }

    public String getItemSpec2() {
        return this.itemSpec2;
    }
    
    public void setItemSpec2(String itemSpec2) {
        this.itemSpec2 = itemSpec2;
    }

    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
   








}