package com.sells.dao;

import java.util.Date;

/**
 * Member generated by MyEclipse - Hibernate Tools
 */
public class Member implements java.io.Serializable {
  // Fields
  private String memberNo;
  private Date joinDt;
  private String ip;
  private String userSeq;

  public String getUserSeq() {
    return userSeq;
  }

  public void setUserSeq(String userSeq) {
    this.userSeq = userSeq;
  }

  private String confirm;
  private String status;
  private Date actDt;
  private String password;
  private String name;
  private String email;
  private String tel;
  private String mobile;
  private String zip;
  private String address;
  private String sellsNo;
  private String birthDt;
  private String epYn;
  private Date modiDt;
  private String modiMan;

  // Constructors
  /** default constructor */
  public Member() {
  }

  /** minimal constructor */
  public Member(String memberNo) {
    this.memberNo = memberNo;
  }

  /** full constructor */
  public Member(String memberNo, Date joinDt, String ip, String confirm,
      String status, Date actDt, String password, String name, String email,
      String tel, String mobile, String zip, String address, String sellsNo,
      String birthDt, String epYn, Date modiDt, String modiMan, String userSeq) {
    this.memberNo = memberNo;
    this.joinDt = joinDt;
    this.ip = ip;
    this.confirm = confirm;
    this.status = status;
    this.actDt = actDt;
    this.password = password;
    this.name = name;
    this.email = email;
    this.tel = tel;
    this.mobile = mobile;
    this.zip = zip;
    this.address = address;
    this.sellsNo = sellsNo;
    this.birthDt = birthDt;
    this.epYn = epYn;
    this.modiDt = modiDt;
    this.modiMan = modiMan;
    this.userSeq = userSeq;
  }

  // Property accessors
  public String getMemberNo() {
    return this.memberNo;
  }

  public void setMemberNo(String memberNo) {
    this.memberNo = memberNo;
  }

  public Date getJoinDt() {
    return this.joinDt;
  }

  public void setJoinDt(Date joinDt) {
    this.joinDt = joinDt;
  }

  public String getIp() {
    return this.ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public String getConfirm() {
    return this.confirm;
  }

  public void setConfirm(String confirm) {
    this.confirm = confirm;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Date getActDt() {
    return this.actDt;
  }

  public void setActDt(Date actDt) {
    this.actDt = actDt;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getTel() {
    return this.tel;
  }

  public void setTel(String tel) {
    this.tel = tel;
  }

  public String getMobile() {
    return this.mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public String getZip() {
    return this.zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }

  public String getAddress() {
    return this.address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public String getSellsNo() {
    return this.sellsNo;
  }

  public void setSellsNo(String sellsNo) {
    this.sellsNo = sellsNo;
  }

  public String getBirthDt() {
    return this.birthDt;
  }

  public void setBirthDt(String birthDt) {
    this.birthDt = birthDt;
  }

  public String getEpYn() {
    return this.epYn;
  }

  public void setEpYn(String epYn) {
    this.epYn = epYn;
  }

  public Date getModiDt() {
    return this.modiDt;
  }

  public void setModiDt(Date modiDt) {
    this.modiDt = modiDt;
  }

  public String getModiMan() {
    return this.modiMan;
  }

  public void setModiMan(String modiMan) {
    this.modiMan = modiMan;
  }
}