package com.sells.dao;



/**
 * OrdersMsgId generated by MyEclipse - Hibernate Tools
 */

public class OrdersMsgId  implements java.io.Serializable {


    // Fields    

     private String orderNo;
     private Integer seq;


    // Constructors

    /** default constructor */
    public OrdersMsgId() {
    }

    
    /** full constructor */
    public OrdersMsgId(String orderNo, Integer seq) {
        this.orderNo = orderNo;
        this.seq = seq;
    }

   
    // Property accessors

    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdersMsgId) ) return false;
		 OrdersMsgId castOther = ( OrdersMsgId ) other; 
         
		 return ( (this.getOrderNo()==castOther.getOrderNo()) || ( this.getOrderNo()!=null && castOther.getOrderNo()!=null && this.getOrderNo().equals(castOther.getOrderNo()) ) )
 && ( (this.getSeq()==castOther.getSeq()) || ( this.getSeq()!=null && castOther.getSeq()!=null && this.getSeq().equals(castOther.getSeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrderNo() == null ? 0 : this.getOrderNo().hashCode() );
         result = 37 * result + ( getSeq() == null ? 0 : this.getSeq().hashCode() );
         return result;
   }   





}