package com.sells.dao;

import java.util.Date;


/**
 * SellsRec generated by MyEclipse - Hibernate Tools
 */

public class SellsRec  implements java.io.Serializable {


    // Fields    

     private String sellsNo;
     private String payAccount;
     private String payDate;
     private Date updateDt;


    // Constructors

    /** default constructor */
    public SellsRec() {
    }

	/** minimal constructor */
    public SellsRec(String sellsNo) {
        this.sellsNo = sellsNo;
    }
    
    /** full constructor */
    public SellsRec(String sellsNo, String payAccount, String payDate, Date updateDt) {
        this.sellsNo = sellsNo;
        this.payAccount = payAccount;
        this.payDate = payDate;
        this.updateDt = updateDt;
    }

   
    // Property accessors

    public String getSellsNo() {
        return this.sellsNo;
    }
    
    public void setSellsNo(String sellsNo) {
        this.sellsNo = sellsNo;
    }

    public String getPayAccount() {
        return this.payAccount;
    }
    
    public void setPayAccount(String payAccount) {
        this.payAccount = payAccount;
    }

    public String getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }

    public Date getUpdateDt() {
        return this.updateDt;
    }
    
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
   








}